runtime: python37
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50
handlers:
- url: /.*
  script: auto
  secure: always

# # update with Redis instance host IP, port
env_variables:
  REDISHOST: 10.0.0.3
  REDISPORT: 6379

# # update with Redis instance network name
env: flex
network:
  name: weather-app-redis