# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:

- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/J-Bowen/weather-app.git']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--verbosity=debug']

- name: 'docker.io/library/python:3.7'
  args:
  - '-m'
  - 'pip'
  - 'install'
  - 'requests'

- name: 'docker.io/library/python:3.7'
  args: ['python', 'test.py']



timeout: 1200s
