# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:

- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/J-Bowen/weather-app.git']

- name: 'docker.io/library/python:2.7'
  args: ['python', 'test.py']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--verbosity=debug']

timeout: 1200s
